#!/opt/bin/perl
use AnyEvent;
use AnyEvent::MP;
use AnyEvent::MP::Global;

initialise_node;

my $find_timer =
   AnyEvent->timer (after => 0, interval => 1, cb => sub {
      my $ports = AnyEvent::MP::Global::find "eg_receivers"
         or return;

      snd $_, test => time
         for @$ports;
   });

AnyEvent->condvar->recv;
