#!/opt/bin/perl
use AnyEvent;
use AnyEvent::MP;
use AnyEvent::MP::Global;

initialise_node "eg_simple_receiver";

my $port = port;

AnyEvent::MP::Global::register $port, "eg_receivers";

rcv $port, test => sub {
   my ($data, $reply_port) = @_;

   print "Received data: " . $data . "\n";
};

AnyEvent->condvar->recv;
